export const palettes = {
  static: [
    "slate",
    "gray",
    "zinc",
    "neutral",
    "stone",
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ] as StaticPalette[],

  staticColor: [
    "red",
    "orange",
    "amber",
    "yellow",
    "lime",
    "green",
    "emerald",
    "teal",
    "cyan",
    "sky",
    "blue",
    "indigo",
    "violet",
    "purple",
    "fuchsia",
    "pink",
    "rose",
  ] as StaticPalette[],

  staticGrayscale: [
    "gray",
    "neutral",
    "slate",
    "stone",
    "zinc",
  ] as GrayscaleStaticPalette[],

  dynamic: ["primary", "off-primary", "off-primary-alt"] as DynamicPalette[],
} as const;
